### ISSUE TITLE
Safari mobile: Main body text is covered by floating header on home page

### ISSUE THREAD

**Issue by jinasuh** [uwscope/scope-web#266]
Issue: On Safari mobile based browsers (any browser on iOS), body text is being covered by floating header (e.g., Tools tab header cover values inventory making it unreachable)

Repro: 

- Log into patient app from any browser on iOS devices (Safari or Chrome)
- The body content starts behind the header
![Broken behavior](https://user-images.githubusercontent.com/9262932/161668152-50f6ef4f-7dfa-47b7-823d-7c32c01a0ad9.png)

Expected: 
The body content starts below the header
![Correct behavior](https://user-images.githubusercontent.com/9262932/161668124-1afba09a-ed2b-41d0-9323-acbe8cc9ab3f.png)

Fix: 
Check safari-mobile specific media filters.

**Comment by jayfo** [comment]
Believed fixed in #269.  To be tested.
