### ISSUE TITLE
Add branding 

### ISSUE THREAD

**Issue by karkar** [uwscope/scope-web#278]
- Remove "Prototype to UW" in registry footer
- Add SCOPE branding "logo or banner depending which is more appropriate" in registry
- Add SCOPE branding "logo or banner depending which is more appropriate" in app
- Add SCOPE logo in the about us page
- Update app so that when people save bookmark to their phone it uses scope logo (for ios and android)

**Comment by jinasuh** [comment]
Removing hamburger menu from the app
