### ISSUE TITLE
Implement assigned -> unassigned functionality

### ISSUE THREAD

**Issue by karkar** [uwscope/scope-web#282]
**Problem**
Registry: once an assessment/inventory/safety plan is assigned, it cannot be unassigned and will persist on patient side till they complete it. 

**Describe Desired Solution**
Once assigned, the clicking the same button again should unassign the item. 

**Describe Alternatives**

**Additional Context**

**Comment by jayfo** [comment]
Duplicate of #336, closed in favor of greater detail there.
