### ISSUE TITLE
Convert Treatment status to a filter in caseload overview

### ISSUE THREAD

**Issue by karkar** [uwscope/scope-web#294]
**Problem**
In a few months when patients start completing/dropping/etc from the study, CMs will need to filter the caseload overview table based on treatment status. 

**Describe Desired Solution**
If we want to be consistent in how we present filters (current filters are SW and clinic) then Tx status should also be a filter/drop-down outside of the table. The Tx status column stays in the table. @garyhsieh can weigh in on the design choice. 

**Describe Alternatives**
Add a dropdown selector in the table header

**Additional Context**
![image](https://user-images.githubusercontent.com/1809636/162793554-477854ce-f527-46eb-a7b7-e84e10830672.png)

**Comment by jayfo** [comment]
This was fixed back in the #331.
