### ISSUE TITLE
Registry navigation panel order does not match content

### ISSUE THREAD

**Issue by karkar** [uwscope/scope-web#299]
**Describe the Bug**
Currently, navigation panel in registry shows `Anxiety` as the first sub-heading under `Progress` even though content shows `Depression` first. 

**To Reproduce**
Open registry and navigate to any patient profile. 

**Expected Behavior**
Navigation should not be organized alphabetically and should display `Depression` as the first sub-heading.

**Screenshots**
![image](https://user-images.githubusercontent.com/1809636/163026913-feebab8d-c69c-462a-841c-d8a376f61e94.png)

**Desktop (provide the following if potentially relevant):**

**Phone (provide the following if potentially relevant):**

**Additional Context**

**Comment by jayfo** [comment]
Fixed in #302.
