### ISSUE TITLE
Activity progress view should show alt activity name when `no, but i did something else` response is selected 

### ISSUE THREAD

**Issue by karkar** [uwscope/scope-web#305]
**Describe the Bug**
When viewing the activity progress of an activity for which the response was `no, but i did something else`, the table should also list what the alt activity was. 

**To Reproduce**
Fill out an activity report with a response of `no, but i did something else`. This works as intended in registry but not in the patient app. 

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1809636/163835152-ede2149a-3efe-45a8-95a3-67e7b655bd24.png)

SS of the thing working as expected in registry
![image](https://user-images.githubusercontent.com/1809636/163835496-bc63e956-f059-4944-98d4-4ab848028045.png)

**Desktop (provide the following if potentially relevant):**

**Phone (provide the following if potentially relevant):**

**Additional Context**

**Comment by jinasuh** [comment]
@karkar I accidentally fixed this for v0.3 milestone. Can we keep this for v0.3?
