### ISSUE TITLE
Blank spaces in 'username' are causing login errors

### ISSUE THREAD

**Issue by karkar** [uwscope/scope-web#312]
**Describe the Bug**
When someone has an extra space character in the username (usually beginning or end), they receive a login error. The error itself is not helpful to the user. 

**To Reproduce**
Try logging in patient app or registry by adding a space before or after username.

**Expected Behavior**
Either provide an explicit error message asking the user to remove the space character or automatically remove it and proceed to authentication

**Screenshots**
![image](https://user-images.githubusercontent.com/1809636/165385029-6d059782-a132-4026-8085-546847fc601c.png)

**Desktop (provide the following if potentially relevant):**
 
**Phone (provide the following if potentially relevant):**
 
**Additional Context**

**Comment by jayfo** [comment]
Fixed in #443.
