### ISSUE TITLE
PHQ/GAD configuration does not accept 'monthly' as a frequency

### ISSUE THREAD

**Issue by karkar** [uwscope/scope-web#326]
**Describe the Bug**

**To Reproduce**
Log in to registry. 
Go to any patient. 
Assign phq/gad if not already assigned. 
Click configure to change assignment.
Set configuration as "monthly". 
Registry behaves as if the operation went through but the text underneath "Depression" heading will read weekly or bi-weekly whatever the previous setting was.

**Expected Behavior**
SWs should be able to assign PHQ/GAD at a frequency of once a month. 
Currently, clicking save with an assessment frequency of "monthly" does nothing.

**Screenshots**
The pink rectangles are me configuring with a frequency of "weekly" and "bi-weekly". Both of those went through fine.
The 400/red text is from when I attempted to configure assessment frequency as "monthly". 
![phq](https://user-images.githubusercontent.com/1809636/173974192-32dd020b-c164-4dc1-945f-24e22aa8162b.png)

**Desktop (provide the following if potentially relevant):**

**Phone (provide the following if potentially relevant):**

**Additional Context**

**Comment by jayfo** [comment]
Schema validation error:

```
{
  "error": {
    "absoluteKeywordLocation": "https://uwscope.org/schemas/assessment#",
    "errors": [
      {
        "absoluteKeywordLocation": "https://uwscope.org/schemas/enums#/properties/assessmentFrequency/enum",
        "error": "The instance value must be equal to one of the elements in the defined enumeration",
        "instanceLocation": "/frequency",
        "keywordLocation": "/properties/frequency/$ref/enum"
      }
    ],
    "instanceLocation": "",
    "keywordLocation": "",
    "valid": false
  },
  "message": "Schema validation failed.",
  "request": {
    "assessment": {
      "_rev": 2,
      "_set_id": "phq-9",
      "_type": "assessment",
      "assessmentId": "phq-9",
      "assigned": true,
      "assignedDateTime": "2022-06-16T13:14:31.787Z",
      "dayOfWeek": "Monday",
      "frequency": "Monthly"
    }
  }
}
```
