### ISSUE TITLE
Update ‘Crisis Help’ in Tools and Depression Check-In

### ISSUE THREAD

**Issue by Taetertot** [uwscope/scope-web#330]
**Need for Optimization**
Crisis number has been updated

**Current**
Under Crisis Help in Tools

![image](https://user-images.githubusercontent.com/68134629/181307300-cd2486ee-e1ac-40d1-8d47-f7ece86dee2d.png)

Under Crisis Resources of Depression Check-In summary

**Describe Desired Optimization**
_Include new 988 crisis number:_ 

**Under Crisis Help in Tools**

![image](https://user-images.githubusercontent.com/68134629/181307822-8822fa87-ec09-428b-b75b-674e5184c1e2.png)

- Call 988 or 1-800-273-TALK (8255)
- Crisis Text Line - Text 988 or Text "HOME" to 741741 

**Under Crisis Resources of Depression Check-In summary:** 

![image](https://user-images.githubusercontent.com/68134629/181309279-0ff5ac8c-a070-4ff5-977e-a96e5c1625b4.png)

- Call National Suicide Prevention Lifeline by phone:  988 or
- Crisis Text Line - Text 988 or "HOME" to 741741 

**Describe Alternatives**
None

**Additional Context**
N/a

**Comment by karkar** [comment]
@Taetertot when mentioning something that needs to be updated, provide the current description. What tab/page is this located in? It helps ensure there is no miscommunication. Also, add image(s) when possible. For this issue, I would take a screenshot of the current crisis help page. For adding images, copy to clipboard and just paste it in the description and it will automatically handle it. No need to upload somewhere and get URL.
