### ISSUE TITLE
Action when patients are done with the study

### ISSUE THREAD

**Issue by Taetertot** [uwscope/scope-web#331]
**Problem**
There is not standard practice  on what to do with patient's accounts when they leave or are done with the study

**Describe Desired Solution**
Gary suggested greying out the accounts that are no longer part of the study, but noted we might need a flag to allow for sorting or something

**Describe Alternatives**

**Additional Context**
Talk about this on Monday 7/31/22

**Comment by jinasuh** [comment]
Use TreatmentStatus == "End"

**Comment by jinasuh** [comment]
Option 1: Checkbox (filled by default) to filter out participants who are no longer in the study (space + next to drop downs)
Option 2: Gray out and move to the bottom of the list

Will go with option 1
