### ISSUE TITLE
Changing wording of Medication Changes in the Registry 

### ISSUE THREAD

**Issue by Taetertot** [uwscope/scope-web#347]
A SW has asked in the Registry under the session notes " instead of calling it 'Medication Changes', change it to 'Medication Notes.' Calling it 'Medication Changes' implies that it will be updated in the 'Current Medications' list, which it is not.
![image](https://user-images.githubusercontent.com/68134629/185293888-9feffeaa-379a-4cda-9f1d-954608eee9fb.png)

**Comment by jayfo** [comment]
Discussed 8/22, Jesse agreed "Medication Notes" seems good.

**Comment by jayfo** [comment]
Discussed w/ @Taetertot on 8/23, decided need to ask about "Behavioral strategy changes" and "Referral changes".

**Comment by jayfo** [comment]
In design discussions, decision is:

Session Information:  Change "Medication Changes" -> "Medication Notes"
Case Review:  No change to "Medication Changes"
Registry Table:  Change Column Header "Med<br>Changes" -> "Medication<br>Changes / Notes"

Fix capitalization while we're there
