### ISSUE TITLE
Sound Verification for task completion for positive reinforcement 

### ISSUE THREAD

**Issue by Taetertot** [uwscope/scope-web#348]
**Problem**
SW ask "If a sound/chime could be provided for patients each time they mark that they have completed a "task", it would be helpful in acknowledging their success while providing a release of dopamine; supporting pleasurable reward, motivation, and potentially aiding in pain relief."

I'm assuming they meant activities, but could also mean the check ins

**Describe Desired Solution**
After submitting a noise will sound
![image](https://user-images.githubusercontent.com/68134629/185294735-ab10fa2e-944d-448a-92fa-f177cf8e2d9b.png)

**Describe Alternatives**
A visual of their task completion  

**Additional Context**

**Comment by jayfo** [comment]
At the core of this is a desire to provide more positive feedback when people successfully complete activities.

Let's keep this as a `wontfix`, close it out when we decide if/how to provide other panels for positive feedback.
