### ISSUE TITLE
Patient Report Needing to Login Each Time they Access App

### ISSUE THREAD

**Issue by Taetertot** [uwscope/scope-web#349]
**Problem**
SW has complained on patients behalf 
"Patient frustrated with app experience: web-based, and must use password each time (and pt is tech-savvy).

**Describe Desired Solution**

**Describe Alternatives**

**Additional Context**
I am not sure what they are frustrated about.

**Comment by jayfo** [comment]
Although this patient is described as tech savy, this really sounds like they are not saving the app to their home screen? I'm not sure why else it wouldn't be saving their password for them?

**Comment by jayfo** [comment]
Did this come in via L?  Could L check that with the patient?

**Comment by jayfo** [comment]
Discussed w/ full team on 8/22, decided this was likely confusion about not putting the app on their home screen.

Agreed to not track as a bug.
