### ISSUE TITLE
Add Safety Notice and Resources in Mood Tracking

### ISSUE THREAD

**Issue by Taetertot** [uwscope/scope-web#398]
**Problem**
Patients can submit crisis notes without proper notice that it won't be seen  

**Describe Desired Solution**
"Please include a disclaimer in Mood Tracking that states that this feature should NOT be used to report a crisis or suicidal thoughts to the social worker." per Social Worker

Add to the end of the Notes verbiage:
‘… This information will be available to your clinical social worker (responses may not be reviewed right away).’

Change the Thank You pop-up to:
‘Thank you for checking in. If you are in crisis or need immediate help, click here for crisis resources.’
(link will take them to the Crisis Help page in the Tools tab)

**Describe Alternatives**

**Additional Context**

**Comment by jayfo** [comment]
Fixed in #430.
