### ISSUE TITLE
Value Names are Not Trimmed Prior to Creation

### ISSUE THREAD

**Issue by jayfo** [uwscope/scope-web#428]
**Describe the Bug**
Observed in v0.7.0, the "name" field of a value document is not being trimmed prior to creation.

**Expected Behavior**
Names should be trimmed, both for appearances and for uniqueness detection.

**Additional Context**
Adding a warning in data validation to monitor this until it is fixed.  See #427.

**Comment by jayfo** [comment]
Check whether this is fixed as part of #416

**Comment by anantmittal** [comment]
I checked that it isn't.

**Comment by jayfo** [comment]
Fixed in #416.

**Comment by jayfo** [comment]
Restored validation in #460.
