### ISSUE TITLE
Include date of study enrollment (or End) in Caseload Overview

### ISSUE THREAD

**Issue by Taetertot** [uwscope/scope-web#473]
**Problem**
SW aren't able to easily see when a patient is about to be leaving the study and this causes issues with administering  proper care and follow up 

![image](https://github.com/uwscope/scope-web/assets/68134629/98f97c4c-2eed-4a82-a063-be7e54f9d919)

**Describe Desired Solution**
- Use "Randomization Date" field from Redcap for this.
- Plan for study staff to back-populate new field in existing patients.
- After they do that, the field will become required.

- Let's call this "Enrollment Date", run that past the team before we ship it.
- Add a date selector at the bottom of "Edit Patient Information" dialog.
- Include in left bar summary of the patient.
- And add a sortable column to the caseload overview.

**Comment by jayfo** [comment]
Fixed in #485
