### ISSUE TITLE
Import paths should be absolute not relative

### ISSUE THREAD

**Issue by jinasuh** [uwscope/scope-web#5]
Relative paths for imports create more headache when moving files around. Make everything absolute, so we don't get confused counting how many directories we need to traverse up and down.

**Comment by jayfo** [comment]
Sounds great.

Is this something we "just do", or could we also set up a linter / test?

I've never actually set up a linter.

**Comment by jinasuh** [comment]
This is just something we configure during compilation/packaging. But we should also set up a linter/test separately. Creating an issue.
